paya_comments = [
    "Uff que rico y tiene que contar un relato mas largo ☺️😊",
    "Si el Cosplay de Gohan para el Rutumbar Tucuman para el Boliche 😎",
    "Puede ser nelson, viejos verde en el buss y flander",
    "Me copa desde Chile y me dan spam de página de nopor encima tiene su historial de familia entre familia wtf que tiene en la cabeza ese chabon con mi correo ve nopor entre familia ! Cada loco en este mundo xD",
    "Ayer corte el streming por querer matar una araña en el enchufe de luz por meter un cuchillo 😂🤣 no se que paso cabeza decir no bole casi prendo fuego 😂🤣 lo siento mucho por corta el streming pero estoy bien sin heridas",
    "pobresito! menos futbol amigo sos un copa verdad? no llenaste B nacional campeones pero vacio 38 fechas",
    "sos un copa verdad? no llenaste B nacional campeones pero vacio 38 fechas",
    "La verdad que si, es un buen juego para pasar el rato y divertirse",
    "Antes de hablar de mi persona si escribo mal o de lo que sean mis defectos primero fíjate de tu club chiquito lloro una copa Federal como sera ni Ole te ha reconocido al titulo muerto peor es ser virgen de copa nacional ese dolor no te lo saca mas 🤣😂",
    "Hola buenos días a todos/a todas espero que este bien y un feliz Viernes Gente! Me levante temprano esperando a alguien pero nunca aparecio es GG al dope 😤",
    "ESGG",
    "FENÓMENO BARRIAL",
    "Recien vengo de correr un ratito 💪🏻",
    "Una vergüenza la organización ahora dirigencia de San Martín le vendio esta eso?",
    "👊🏻 RT Si apoyas el uno menos  👊🏻 Like si apoyas el uno menos 👊🏻 Comenta si apoyas el uno menos",
    "ya saben vendieron el partido como final y cuarto de final es GG gente ! verguenza la dirigencia de San Martin por favor Milei hace SA a todo el futbol Argentino",
    "Hola buenas tardes a todos/a todas espero que este bien y un feliz Viernes Gente! Hermosa Tarde con el Goku Adulto y Vegeta Adulto es Gg volvieron a romper el internet 🚬Es Cine😎",
    "@SergioMassa muchas gracias por romper la Moneda ahora los Gamer no podremos comprar Juegos en Steam por que antes había menos impuesto con nuestra moneda pero ahora es 100% de impuesto antes era 85% pero se podia comprar algo ahora imposible 💔😭",
    "Con La chica Elen que compartir en el Estadio mas Caliente del Pais re piolas 🇦🇹 ⚽ 🇦🇷 buena amistad 💪🏻",
    "Aun sigue jugando ese jugador! Ahora se queja por horarios wtf y hace un año juegas en el club no acostumbras a jugar con el clima tucumano 😤",
    "Disfrutando lo votado y vos kukardo?",
    "No me gusta la politica pero hoy Murio Javier Milei por juntarse con la Patricia bullrich no me gusta nada de nada eso seria una Alemania Nazi por lejos asi mi Voto sera en Blanco y la verdad Massa tampoco no me gusta era solo eso nomas fin del comunicado .",
    "estube un ratito de niñero de mi hija de mi prima se iba re lejos sin decir nada estube siguiendo mal para que no se pierda se parece ami cuando no me gusta algo me voy a caminar por ahi xD",
    "#NocheDeConfesiones la primera mujer es mi prima y ella me saco la virginidad xD"
]